name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Run CI
        run: pnpm run ci --concurrency=100%
